backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: content/images
public_folder: images
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "intro", label: "Summary", widget: "string" }
      - {
          name: "postedAt",
          label: "Posted At",
          widget: "datetime",
          format: "x",
        }
      - { name: "news", label: "News", widget: "boolean" }
      - { name: "description", label: "Meta Description", widget: "string" }
      - { name: "keywords", label: "Meta Keywords", widget: "string" }
      - { name: "altText", label: "Image ALT text", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image" }
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Meta Description", widget: "string" }
      - { name: "keywords", label: "Meta Keywords", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    format: "json"
    extension: ".json"
    create: true
    fields:
      - { name: "image", label: "Image", widget: "image" }
      - { name: "title", label: "Title", widget: "string" }
      - { label: "Testimony", name: "text", widget: "markdown" }
  - name: "site"
    label: "Site Data"
    files:
      - name: "pillars"
        label: "pillars"
        file: "content/site/pillars.yaml"
        minimize_collapsed: true
        fields:
          - name: "pillars"
            label: "Pillars"
            widget: "list"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - {
                  name: "fronttitle",
                  label: "Front-Page Title",
                  widget: "string",
                }
              - { name: "id", label: "id", widget: "string" }
              - { name: "image", label: "Image", widget: "image" }
              - { name: "examples", label: "Examples", widget: "list" }
              - { name: "frontpage", label: "Frontpage", widget: "boolean" }
              - { name: "industry", label: "Industry", widget: "boolean" }
              - name: "moreguides"
                label: "More Guides"
                widget: "list"
                fields:
                  - { name: "title", label: "Title", widget: "string" }
                  - {
                      name: "url",
                      label: "Destination",
                      required: false,
                      widget: "string",
                    }
      - name: "links"
        label: "Links"
        file: "content/site/links.yaml"
        widget: "object"
        summary: "{{fields.label}}"
        fields:
          - name: "shippingservices"
            label: "Shipping Services"
            widget: "list"
            minimize_collapsed: true
            fields:
              - name: "title"
                label: "Title"
                widget: "string"
              - name: "url"
                label: "URL"
                widget: "string"
          - name: "morelinks"
            label: "More Links"
            widget: "list"
            minimize_collapsed: true
            fields:
              - name: "title"
                label: "Title"
                widget: "string"
              - name: "url"
                label: "URL"
                widget: "string"
          - name: "resourceslinks"
            label: "Resource Links"
            widget: "list"
            minimize_collapsed: true
            fields:
              - name: "title"
                label: "Title"
                widget: "string"
              - name: "url"
                label: "URL"
