backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: content/images
public_folder: images
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    format: "json-frontmatter"
    extension: ".json"
    create: true
    fields:
      - { name: "image", label: "Image", widget: "image" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "intro", label: "Intro", widget: "string" }
      - { name: "postedAt", label: "Posted At", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
